package dk.trustworks.invoicewebui.web.mainmenu.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.v7.ui.Label;
import com.vaadin.ui.Button;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class BreadcrumBarDesign extends HorizontalLayout {
    private Button btnIcon;
    private Label lblTitle;
    private Label lblBreadcrum;

    public BreadcrumBarDesign() {
        Design.read(this);
    }

    public Button getBtnIcon() {
        return btnIcon;
    }

    public Label getLblTitle() {
        return lblTitle;
    }

    public Label getLblBreadcrum() {
        return lblBreadcrum;
    }

}
