package dk.trustworks.invoicewebui.web.mainmenu.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MenuItemDesign extends HorizontalLayout {
    private Label lblChildSpace;
    private Button btnMenuitemText;
    private Button btnParentIndicator;

    public MenuItemDesign() {
        Design.read(this);
    }

    public Label getLblChildSpace() {
        return lblChildSpace;
    }

    public Button getBtnMenuitemText() {
        return btnMenuitemText;
    }

    public Button getBtnParentIndicator() {
        return btnParentIndicator;
    }

}
