package dk.trustworks.invoicewebui.web.login.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.*;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ForgotPasswordDesign extends CssLayout {
    private VerticalLayout cardHolder;
    private Image imgTop;
    private VerticalLayout vlReset;
    private TextField txtUsername;
    private TextField txtPassword;
    private TextField txtConfirmPassword;
    private Button btnLogin;
    private HorizontalLayout hlBackToLogin;
    private VerticalLayout vlConfirmation;

    public ForgotPasswordDesign() {
        Design.read(this);
    }

    public VerticalLayout getCardHolder() {
        return cardHolder;
    }

    public Image getImgTop() {
        return imgTop;
    }

    public VerticalLayout getVlReset() {
        return vlReset;
    }

    public TextField getTxtUsername() {
        return txtUsername;
    }

    public TextField getTxtPassword() {
        return txtPassword;
    }

    public TextField getTxtConfirmPassword() {
        return txtConfirmPassword;
    }

    public Button getBtnLogin() {
        return btnLogin;
    }

    public HorizontalLayout getHlBackToLogin() {
        return hlBackToLogin;
    }

    public VerticalLayout getVlConfirmation() {
        return vlConfirmation;
    }

}
