package dk.trustworks.invoicewebui.web.dashboard.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Image;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class BubbleRowDesign extends HorizontalLayout {
    private HorizontalLayout hlBackground;
    private HorizontalLayout hlNameBackground;
    private CssLayout cssBubblePhotoContainer;
    private Image imgBubblePhoto;
    private Label lblName;
    private Label txtMembers;
    private VerticalLayout vlOwner;
    private CssLayout cssOwnerPhotoContainer;

    public BubbleRowDesign() {
        Design.read(this);
    }

    public HorizontalLayout getHlBackground() {
        return hlBackground;
    }

    public HorizontalLayout getHlNameBackground() {
        return hlNameBackground;
    }

    public CssLayout getCssBubblePhotoContainer() {
        return cssBubblePhotoContainer;
    }

    public Image getImgBubblePhoto() {
        return imgBubblePhoto;
    }

    public Label getLblName() {
        return lblName;
    }

    public Label getTxtMembers() {
        return txtMembers;
    }

    public VerticalLayout getVlOwner() {
        return vlOwner;
    }

    public CssLayout getCssOwnerPhotoContainer() {
        return cssOwnerPhotoContainer;
    }

}
