package dk.trustworks.invoicewebui.web.dashboard.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Button;
import com.vaadin.ui.Image;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class NotificationPopupDesign extends VerticalLayout {
    private VerticalLayout cardHolder;
    private Image imgNotification;
    private Label lblDescription;
    private Label lblDetails;
    private Button btndismiss;

    public NotificationPopupDesign() {
        Design.read(this);
    }

    public VerticalLayout getCardHolder() {
        return cardHolder;
    }

    public Image getImgNotification() {
        return imgNotification;
    }

    public Label getLblDescription() {
        return lblDescription;
    }

    public Label getLblDetails() {
        return lblDetails;
    }

    public Button getBtndismiss() {
        return btndismiss;
    }

}
