package dk.trustworks.invoicewebui.web.dashboard.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Button;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ReleaseNotesPopupDesign extends VerticalLayout {
    private Image imgNotification;
    private Label lblReleaseNote;
    private Button btndismiss;

    public ReleaseNotesPopupDesign() {
        Design.read(this);
    }

    public Image getImgNotification() {
        return imgNotification;
    }

    public Label getLblReleaseNote() {
        return lblReleaseNote;
    }

    public Button getBtndismiss() {
        return btndismiss;
    }

}
