server:
  port: ${PORT:4444}

spring:
  application:
    name: time-service
  logging:
    pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    level:
      org.springframework: WARN
      org.hibernate: WARN
  jpa:
    hibernate.ddl-auto: none
  datasource:
    url: jdbc:mysql://trustworksdb.cm3iylt6ulsl.eu-west-1.rds.amazonaws.com:3306/timemanager?noDatetimeStringSync=true&characterEncoding=utf8
    username: root
    password: TqNu)dV6BERQ7PXG
    hikari:
      maximum-pool-size: 2

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

ribbon:
  eureka:
    enabled: true

# Logging
logging:
  level:
    org:
      springframework:
        cloud:
          client:
            hypermedia: DEBUG


management.security.enabled: false