package dk.trustworks.invoicewebui.web.contracts.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.TextField;
import com.vaadin.ui.ComboBox;
import com.vaadin.annotations.PropertyId;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ConsultantDesign extends VerticalLayout {
    @PropertyId("username")
    private ComboBox<dk.trustworks.invoicewebui.model.User> cbConsultant;
    private TextField txtRate;
    private Button btnUpdate;
    private Button btnDelete;
    private Button btnCreate;

    public ConsultantDesign() {
        Design.read(this);
    }

    public ComboBox<dk.trustworks.invoicewebui.model.User> getCbConsultant() {
        return cbConsultant;
    }

    public TextField getTxtRate() {
        return txtRate;
    }

    public Button getBtnUpdate() {
        return btnUpdate;
    }

    public Button getBtnDelete() {
        return btnDelete;
    }

    public Button getBtnCreate() {
        return btnCreate;
    }

}
