package dk.trustworks.invoicewebui.web.contracts.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBoxGroup;
import com.vaadin.annotations.PropertyId;
import com.vaadin.ui.Panel;
import com.vaadin.ui.HorizontalLayout;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ContractDesign extends VerticalLayout {
    private CssLayout cardHolder;
    private Label lblTitle;
    private Button btnExtendContract;
    private VerticalLayout container;
    private Label lblContractNumber;
    private Label lblType;
    @PropertyId("name")
    private CheckBoxGroup<dk.trustworks.invoicewebui.model.Project> chkProjects;
    private Label lblPeriod;
    private Label lblAmount;
    private Panel photosContentHolder;
    private HorizontalLayout photoContainer;
    private Button btnEdit;
    private Button btnDelete;

    public ContractDesign() {
        Design.read(this);
    }

    public CssLayout getCardHolder() {
        return cardHolder;
    }

    public Label getLblTitle() {
        return lblTitle;
    }

    public Button getBtnExtendContract() {
        return btnExtendContract;
    }

    public VerticalLayout getContainer() {
        return container;
    }

    public Label getLblContractNumber() {
        return lblContractNumber;
    }

    public Label getLblType() {
        return lblType;
    }

    public CheckBoxGroup<dk.trustworks.invoicewebui.model.Project> getChkProjects() {
        return chkProjects;
    }

    public Label getLblPeriod() {
        return lblPeriod;
    }

    public Label getLblAmount() {
        return lblAmount;
    }

    public Panel getPhotosContentHolder() {
        return photosContentHolder;
    }

    public HorizontalLayout getPhotoContainer() {
        return photoContainer;
    }

    public Button getBtnEdit() {
        return btnEdit;
    }

    public Button getBtnDelete() {
        return btnDelete;
    }

}
