package dk.trustworks.invoicewebui.web.contracts.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ContactInformationRowDesign extends VerticalLayout {
    private Label lblName;
    private Label lblContact;
    private Label lblCVR;
    private Label lblEAN;
    private Label lblStreet;
    private Label lblPostalCode;
    private Label lblCity;
    private Label lblOther;
    private Button btnChange;

    public ContactInformationRowDesign() {
        Design.read(this);
    }

    public Label getLblName() {
        return lblName;
    }

    public Label getLblContact() {
        return lblContact;
    }

    public Label getLblCVR() {
        return lblCVR;
    }

    public Label getLblEAN() {
        return lblEAN;
    }

    public Label getLblStreet() {
        return lblStreet;
    }

    public Label getLblPostalCode() {
        return lblPostalCode;
    }

    public Label getLblCity() {
        return lblCity;
    }

    public Label getLblOther() {
        return lblOther;
    }

    public Button getBtnChange() {
        return btnChange;
    }

}
