package dk.trustworks.invoicewebui.web.contracts.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import dk.trustworks.invoicewebui.model.enums.ContractStatus;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.TextField;
import com.vaadin.ui.DateField;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.Button;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ContractFormDesign extends VerticalLayout {
    private CssLayout cardHolder;
    private Label lblTitle;
    private VerticalLayout container;
    private ComboBox<dk.trustworks.invoicewebui.model.enums.ContractType> cbType;
    private ComboBox<ContractStatus> cbStatus;
    private ComboBox<dk.trustworks.invoicewebui.model.User> cbSalesConsultant;
    private TextField txtRefid;
    private DateField dfFrom;
    private DateField dfTo;
    private TextField txtAmount;
    private TextArea txtNote;
    private Button btnUpdate;
    private Button btnCreate;
    private CssLayout cssNotification;
    private Label lblNotification;

    public ContractFormDesign() {
        Design.read(this);
    }

    public CssLayout getCardHolder() {
        return cardHolder;
    }

    public Label getLblTitle() {
        return lblTitle;
    }

    public VerticalLayout getContainer() {
        return container;
    }

    public ComboBox<dk.trustworks.invoicewebui.model.enums.ContractType> getCbType() {
        return cbType;
    }

    public ComboBox<ContractStatus> getCbStatus() {
        return cbStatus;
    }

    public ComboBox<dk.trustworks.invoicewebui.model.User> getCbSalesConsultant() {
        return cbSalesConsultant;
    }

    public TextField getTxtRefid() {
        return txtRefid;
    }

    public DateField getDfFrom() {
        return dfFrom;
    }

    public DateField getDfTo() {
        return dfTo;
    }

    public TextField getTxtAmount() {
        return txtAmount;
    }

    public TextArea getTxtNote() {
        return txtNote;
    }

    public Button getBtnUpdate() {
        return btnUpdate;
    }

    public Button getBtnCreate() {
        return btnCreate;
    }

    public CssLayout getCssNotification() {
        return cssNotification;
    }

    public Label getLblNotification() {
        return lblNotification;
    }

}
