package dk.trustworks.web.views;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.GridLayout;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class InvoicePreview extends AbsoluteLayout {
    protected Label lblClientname;
    protected Label lblStreet;
    protected Label lblZipCity;
    protected Label lblCvrEan;
    protected Label lblAttention;
    protected Label lblDescription;
    protected GridLayout glInvoiceItems;
    protected Label lblTotal;
    protected Button btnAction;
    protected Label lblStatus;

    public InvoicePreview() {
        Design.read(this);
    }

}
