package dk.trustworks.web.views;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Grid;
import com.vaadin.ui.CssLayout;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class InvoiceListDesign_old extends VerticalLayout {
    protected ComboBox<dk.trustworks.web.model.YearMonthSelect> cbSelectYearMonth;
    protected Grid<dk.trustworks.network.dto.Invoice> gridInvoiceList;
    protected CssLayout invoicePreviewContainer;

    public InvoiceListDesign_old() {
        Design.read(this);
    }
}
