package dk.trustworks.invoicewebui.web.knowledge.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Image;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ArchitectureCell extends VerticalLayout {
    private VerticalLayout cardHolder;
    private Image imgTop1;
    private Image imgTop2;
    private VerticalLayout vlContent1;
    private VerticalLayout vlContent2;
    private VerticalLayout contentHolder;

    public ArchitectureCell() {
        Design.read(this);
    }

    public VerticalLayout getCardHolder() {
        return cardHolder;
    }

    public Image getImgTop1() {
        return imgTop1;
    }

    public Image getImgTop2() {
        return imgTop2;
    }

    public VerticalLayout getVlContent1() {
        return vlContent1;
    }

    public VerticalLayout getVlContent2() {
        return vlContent2;
    }

    public VerticalLayout getContentHolder() {
        return contentHolder;
    }

}
