package dk.trustworks.invoicewebui.web.time.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.DateField;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.TextArea;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class CustomerExpensesGrid extends HorizontalLayout {
    private DateField dfReceiptDate;
    private ComboBox<dk.trustworks.invoicewebui.model.Project> cbProject;
    private TextArea txtDescription;
    private TextField txtAmount;
    private Button btnAddReceipt;
    private GridLayout gridExistingReceipts;

    public CustomerExpensesGrid() {
        Design.read(this);
    }

    public DateField getDfReceiptDate() {
        return dfReceiptDate;
    }

    public ComboBox<dk.trustworks.invoicewebui.model.Project> getCbProject() {
        return cbProject;
    }

    public TextArea getTxtDescription() {
        return txtDescription;
    }

    public TextField getTxtAmount() {
        return txtAmount;
    }

    public Button getBtnAddReceipt() {
        return btnAddReceipt;
    }

    public GridLayout getGridExistingReceipts() {
        return gridExistingReceipts;
    }

}
