package dk.trustworks.invoicewebui.web.time.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Grid;
import com.vaadin.annotations.PropertyId;
import com.vaadin.ui.Label;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class TimeManagerDesign extends VerticalLayout {
    private Label lblCurrentDate;
    private Button btnWeekNumberDecr;
    private TextField txtWeekNumber;
    private Button btnWeekNumberIncr;
    private Button btnYearDecr;
    private TextField txtYear;
    private Button btnYearIncr;
    @PropertyId("username")
    private ComboBox<dk.trustworks.invoicewebui.network.dto.User> selActiveUser;
    private Button btnAddTask;
    private Grid<dk.trustworks.invoicewebui.web.time.model.WeekItem> gridTimeTable;
    private TextField lblTotalHours;

    public TimeManagerDesign() {
        Design.read(this);
    }

    public Label getLblCurrentDate() {
        return lblCurrentDate;
    }

    public Button getBtnWeekNumberDecr() {
        return btnWeekNumberDecr;
    }

    public TextField getTxtWeekNumber() {
        return txtWeekNumber;
    }

    public Button getBtnWeekNumberIncr() {
        return btnWeekNumberIncr;
    }

    public Button getBtnYearDecr() {
        return btnYearDecr;
    }

    public TextField getTxtYear() {
        return txtYear;
    }

    public Button getBtnYearIncr() {
        return btnYearIncr;
    }

    public ComboBox<dk.trustworks.invoicewebui.network.dto.User> getSelActiveUser() {
        return selActiveUser;
    }

    public Button getBtnAddTask() {
        return btnAddTask;
    }

    public Grid<dk.trustworks.invoicewebui.web.time.model.WeekItem> getGridTimeTable() {
        return gridTimeTable;
    }

    public TextField getLblTotalHours() {
        return lblTotalHours;
    }

}
