package dk.trustworks.invoicewebui.web.invoice.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class InvoiceListItem extends HorizontalLayout {
    private VerticalLayout trafficLight;

    private VerticalLayout trafficLightRef;

    private Label lblProjectName;
    private Label lblAmount;
    private Label lblDescription;
    private Label lblInvoicedAmount;

    public InvoiceListItem() {
        Design.read(this);
    }

    public VerticalLayout getTrafficLight() {
        return trafficLight;
    }

    public VerticalLayout getTrafficLightRef() {
        return trafficLightRef;
    }

    public Label getLblProjectName() {
        return lblProjectName;
    }

    public Label getLblAmount() {
        return lblAmount;
    }

    public Label getLblDescription() {
        return lblDescription;
    }

    public Label getLblInvoicedAmount() {
        return lblInvoicedAmount;
    }

}
