package dk.trustworks.invoicewebui.web.invoice.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Grid;
import com.vaadin.ui.Button;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class InvoiceListDesign extends VerticalLayout {
    protected Button btnTour;
    protected Grid<dk.trustworks.invoicewebui.model.Invoice> gridInvoiceList;
    protected Button btnDownloadPdf;
    protected Button btnViewPdf;
    protected Button btnCreateCreditNota;
    protected Button btnRecreateInvoice;
    protected Grid<dk.trustworks.invoicewebui.web.model.SubTotal> gridSubTotals;

    public InvoiceListDesign() {
        Design.read(this);
    }

}
