package dk.trustworks.invoicewebui.web.invoice.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.Grid;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Button;
import com.vaadin.ui.VerticalLayout;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class NewInvoiceDesign extends VerticalLayout {
    protected Button btnTour;
    protected ComboBox<dk.trustworks.invoicewebui.web.model.YearMonthSelect> cbSelectYearMonth;
    protected VerticalLayout vlErrorCardContainer;
    protected Grid<dk.trustworks.invoicewebui.network.dto.ProjectSummary> gridProjectSummaryList;
    protected Button btnCreateInvoice;
    protected Button btnCreateBlankInvoice;

    public NewInvoiceDesign() {
        Design.read(this);
    }
}
