package dk.trustworks.invoicewebui.web.common;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Card extends VerticalLayout {
    private VerticalLayout cardHolder;
    private HorizontalLayout hlTitleBar;
    private Label lblTitle;
    private Button btnAlt1;
    private Button btnAlt2;
    private VerticalLayout content;

    public Card() {
        Design.read(this);
    }

    public VerticalLayout getCardHolder() {
        return cardHolder;
    }

    public HorizontalLayout getHlTitleBar() {
        return hlTitleBar;
    }

    public Label getLblTitle() {
        return lblTitle;
    }

    public Button getBtnAlt1() {
        return btnAlt1;
    }

    public Button getBtnAlt2() {
        return btnAlt2;
    }

    public VerticalLayout getContent() {
        return content;
    }

}
