package dk.trustworks.invoicewebui.web.project.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class AddTask extends VerticalLayout {
    private TextField txtTaskName;
    private Button btnCreate;
    private Button btnCancel;

    public AddTask() {
        Design.read(this);
    }

    public TextField getTxtTaskName() {
        return txtTaskName;
    }

    public Button getBtnCreate() {
        return btnCreate;
    }

    public Button getBtnCancel() {
        return btnCancel;
    }

}
