package dk.trustworks.invoicewebui.web.project.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Image;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.ComboBox;
import com.vaadin.annotations.PropertyId;
import com.vaadin.ui.DateField;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.Button;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ProjectDetailCardDesign extends VerticalLayout {
    private CssLayout cardHolder;
    private Label lblTitle;
    private VerticalLayout container;
    private Image logo;
    private FormLayout formProjectDetail;
    private TextField txtName;
    private TextField txtDescription;
    @PropertyId("username")
    private ComboBox<dk.trustworks.invoicewebui.model.User> selRelationManager;
    private DateField selStartDate;
    private DateField selEndDate;
    private TextField txtBudget;
    private CheckBox chkActive;
    private Button btnUpdate;
    private Button btnDelete;

    public ProjectDetailCardDesign() {
        Design.read(this);
    }

    public CssLayout getCardHolder() {
        return cardHolder;
    }

    public Label getLblTitle() {
        return lblTitle;
    }

    public VerticalLayout getContainer() {
        return container;
    }

    public Image getLogo() {
        return logo;
    }

    public FormLayout getFormProjectDetail() {
        return formProjectDetail;
    }

    public TextField getTxtName() {
        return txtName;
    }

    public TextField getTxtDescription() {
        return txtDescription;
    }

    public ComboBox<dk.trustworks.invoicewebui.model.User> getSelRelationManager() {
        return selRelationManager;
    }

    public DateField getSelStartDate() {
        return selStartDate;
    }

    public DateField getSelEndDate() {
        return selEndDate;
    }

    public TextField getTxtBudget() {
        return txtBudget;
    }

    public CheckBox getChkActive() {
        return chkActive;
    }

    public Button getBtnUpdate() {
        return btnUpdate;
    }

    public Button getBtnDelete() {
        return btnDelete;
    }

}
