package dk.trustworks.invoicewebui.web.project.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.ComboBox;
import com.vaadin.annotations.PropertyId;
import com.vaadin.ui.Button;
import com.vaadin.addon.onoffswitch.OnOffSwitch;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ProjectManagerDesign extends VerticalLayout {
    @PropertyId("name")
    private ComboBox<dk.trustworks.invoicewebui.model.Client> selClient;
    @PropertyId("name")
    private ComboBox<dk.trustworks.invoicewebui.model.Project> selProject;
    private OnOffSwitch onOffSwitch;
    private Button btnAddNewProject;

    public ProjectManagerDesign() {
        Design.read(this);
    }

    public ComboBox<dk.trustworks.invoicewebui.model.Client> getSelClient() {
        return selClient;
    }

    public ComboBox<dk.trustworks.invoicewebui.model.Project> getSelProject() {
        return selProject;
    }

    public OnOffSwitch getOnOffSwitch() {
        return onOffSwitch;
    }

    public Button getBtnAddNewProject() {
        return btnAddNewProject;
    }

}
