package dk.trustworks.invoicewebui.web.project.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.HorizontalLayout;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class TaskRowDesign extends VerticalLayout {
    private Button btnIcon;
    private CssLayout cssTaskName;
    private Label lblName;
    private VerticalLayout vlTextTokenField;
    private TextField txtName;
    private TokenListImpl tokenField;
    private Button btnDelete;
    private HorizontalLayout subRow;
    private VerticalLayout hlChart;

    public TaskRowDesign() {
        Design.read(this);
    }

    public Button getBtnIcon() {
        return btnIcon;
    }

    public CssLayout getCssTaskName() {
        return cssTaskName;
    }

    public Label getLblName() {
        return lblName;
    }

    public VerticalLayout getVlTextTokenField() {
        return vlTextTokenField;
    }

    public TextField getTxtName() {
        return txtName;
    }

    public TokenListImpl getTokenField() {
        return tokenField;
    }

    public Button getBtnDelete() {
        return btnDelete;
    }

    public HorizontalLayout getSubRow() {
        return subRow;
    }

    public VerticalLayout getHlChart() {
        return hlChart;
    }

}
