package dk.trustworks.invoicewebui.web.projectdescriptions.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.*;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ProjectDescriptionFormDesign extends VerticalLayout {
    private ComboBox<dk.trustworks.invoicewebui.model.Client> cbClient;
    private TextField txtName;
    private TextArea txtDescription;
    private VerticalLayout vlUserStories;
    private Button btnAddUserStorie;
    private Button btnSave;

    public ProjectDescriptionFormDesign() {
        Design.read(this);
    }

    public ComboBox<dk.trustworks.invoicewebui.model.Client> getCbClient() {
        return cbClient;
    }

    public TextField getTxtName() {
        return txtName;
    }

    public TextArea getTxtDescription() {
        return txtDescription;
    }

    public VerticalLayout getVlUserStories() {
        return vlUserStories;
    }

    public Button getBtnAddUserStorie() {
        return btnAddUserStorie;
    }

    public Button getBtnSave() {
        return btnSave;
    }

}
