package dk.trustworks.invoicewebui.web.projectdescriptions.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.*;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ProjectDescriptionDesign extends VerticalLayout {
    private VerticalLayout cardHolder;
    private Image imgTop;
    private VerticalLayout container;
    private Label lblHeading;
    private HorizontalLayout gaugeContainer;
    private Button btnEdit;
    private Panel textContentHolder;
    private Label lblDescription;
    private Panel photosContentHolder;
    private HorizontalLayout photoContainer;
    private Panel userTextContentHolder;
    private Label lblUserDescription;

    public ProjectDescriptionDesign() {
        Design.read(this);
    }

    public VerticalLayout getCardHolder() {
        return cardHolder;
    }

    public Image getImgTop() {
        return imgTop;
    }

    public VerticalLayout getContainer() {
        return container;
    }

    public Label getLblHeading() {
        return lblHeading;
    }

    public HorizontalLayout getGaugeContainer() {
        return gaugeContainer;
    }

    public Button getBtnEdit() {
        return btnEdit;
    }

    public Panel getTextContentHolder() {
        return textContentHolder;
    }

    public Label getLblDescription() {
        return lblDescription;
    }

    public Panel getPhotosContentHolder() {
        return photosContentHolder;
    }

    public HorizontalLayout getPhotoContainer() {
        return photoContainer;
    }

    public Panel getUserTextContentHolder() {
        return userTextContentHolder;
    }

    public Label getLblUserDescription() {
        return lblUserDescription;
    }

}
