package dk.trustworks.invoicewebui.web.employee.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.DateField;
import com.vaadin.ui.Grid;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class UserMonthReportDesign extends VerticalLayout {
    private VerticalLayout cardHolder;
    private Label lblTitle;
    private DateField date;
    private VerticalLayout container;
    private Grid<dk.trustworks.invoicewebui.web.time.model.UserHourItem> getReportGrid;

    public UserMonthReportDesign() {
        Design.read(this);
    }

    public VerticalLayout getCardHolder() {
        return cardHolder;
    }

    public Label getLblTitle() {
        return lblTitle;
    }

    public DateField getDate() {
        return date;
    }

    public VerticalLayout getContainer() {
        return container;
    }

    public Grid<dk.trustworks.invoicewebui.web.time.model.UserHourItem> getGetReportGrid() {
        return getReportGrid;
    }

}
