package dk.trustworks.invoicewebui.web.employee.components.parts;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.annotations.PropertyId;
import com.vaadin.ui.DateField;
import com.vaadin.ui.TextField;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class AddBudgetItem extends VerticalLayout {
    private VerticalLayout cardHolder;
    private DateField date;
    @PropertyId("longName")
    private ComboBox<dk.trustworks.invoicewebui.model.ITBudgetCategory> cbCategory;
    private TextField txtDescription;
    private TextField txtAmount;
    private Button btnAdd;
    private Button btnCancel;

    public AddBudgetItem() {
        Design.read(this);
    }

    public VerticalLayout getCardHolder() {
        return cardHolder;
    }

    public DateField getDate() {
        return date;
    }

    public ComboBox<dk.trustworks.invoicewebui.model.ITBudgetCategory> getCbCategory() {
        return cbCategory;
    }

    public TextField getTxtDescription() {
        return txtDescription;
    }

    public TextField getTxtAmount() {
        return txtAmount;
    }

    public Button getBtnAdd() {
        return btnAdd;
    }

    public Button getBtnCancel() {
        return btnCancel;
    }

}
