package dk.trustworks.invoicewebui.web.employee.components.parts;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class BudgetItem extends VerticalLayout {
    private VerticalLayout cardHolder;
    private Image imgIcon;
    private Image imgAmortized;
    private Label lblDate;
    private Label lblDescription;
    private Label lblAmortizationPeriod;
    private Label lblAmount;
    private CssLayout vlButtonLayout;
    private Button btnCrashed;
    private Button btnLost;
    private Button btnAmortized;
    private Button btnDelete;

    public BudgetItem() {
        Design.read(this);
    }

    public VerticalLayout getCardHolder() {
        return cardHolder;
    }

    public Image getImgIcon() {
        return imgIcon;
    }

    public Image getImgAmortized() {
        return imgAmortized;
    }

    public Label getLblDate() {
        return lblDate;
    }

    public Label getLblDescription() {
        return lblDescription;
    }

    public Label getLblAmortizationPeriod() {
        return lblAmortizationPeriod;
    }

    public Label getLblAmount() {
        return lblAmount;
    }

    public CssLayout getVlButtonLayout() {
        return vlButtonLayout;
    }

    public Button getBtnCrashed() {
        return btnCrashed;
    }

    public Button getBtnLost() {
        return btnLost;
    }

    public Button getBtnAmortized() {
        return btnAmortized;
    }

    public Button getBtnDelete() {
        return btnDelete;
    }

}
