package dk.trustworks.invoicewebui.web.employee.components.parts;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.Button;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class CKOExpenseItem extends VerticalLayout {
    private VerticalLayout cardHolder;
    private Image imgIcon;
    private Image imgAmortized;
    private Label lblDate;
    private Label lblDays;
    private Label lblDescription;
    private Label lblAmount;
    private Label lblStatus;
    private Label lblAmortizationPeriod1;
    private Label lblAmortizationPeriod11;
    private CssLayout vlButtonLayout;
    private Button btnEdit;
    private Button btnDelete;

    public CKOExpenseItem() {
        Design.read(this);
    }

    public VerticalLayout getCardHolder() {
        return cardHolder;
    }

    public Image getImgIcon() {
        return imgIcon;
    }

    public Image getImgAmortized() {
        return imgAmortized;
    }

    public Label getLblDate() {
        return lblDate;
    }

    public Label getLblDays() {
        return lblDays;
    }

    public Label getLblDescription() {
        return lblDescription;
    }

    public Label getLblAmount() {
        return lblAmount;
    }

    public Label getLblStatus() {
        return lblStatus;
    }

    public Label getLblAmortizationPeriod1() {
        return lblAmortizationPeriod1;
    }

    public Label getLblAmortizationPeriod11() {
        return lblAmortizationPeriod11;
    }

    public CssLayout getVlButtonLayout() {
        return vlButtonLayout;
    }

    public Button getBtnEdit() {
        return btnEdit;
    }

    public Button getBtnDelete() {
        return btnDelete;
    }

}
