package dk.trustworks.invoicewebui.web.employee.components.parts;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ConfirmSpeedDateDesign extends VerticalLayout {
    private VerticalLayout cardHolder;
    private Label lblDescription;
    private Button btnDidIt;
    private Button btnNope;

    public ConfirmSpeedDateDesign() {
        Design.read(this);
    }

    public VerticalLayout getCardHolder() {
        return cardHolder;
    }

    public Label getLblDescription() {
        return lblDescription;
    }

    public Button getBtnDidIt() {
        return btnDidIt;
    }

    public Button getBtnNope() {
        return btnNope;
    }

}
