package dk.trustworks.invoicewebui.web.employee.components.parts;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Button;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class DocumentDesign extends VerticalLayout {
    private VerticalLayout cardHolder;
    private Image imgIcon;
    private Label lblDate;
    private Label lblDescription;
    private Label lblType;
    private Button btnDownload;

    public DocumentDesign() {
        Design.read(this);
    }

    public VerticalLayout getCardHolder() {
        return cardHolder;
    }

    public Image getImgIcon() {
        return imgIcon;
    }

    public Label getLblDate() {
        return lblDate;
    }

    public Label getLblDescription() {
        return lblDescription;
    }

    public Label getLblType() {
        return lblType;
    }

    public Button getBtnDownload() {
        return btnDownload;
    }

}
