package dk.trustworks.invoicewebui.web.client.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.FormLayout;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ClientDataDesign extends VerticalLayout {
    private VerticalLayout cardHolder;
    private Label lblTitle;
    private VerticalLayout container;
    private TextField txtName;
    private TextField txtContactName;
    private Button btnEdit;
    private CssLayout cssHider;
    private FormLayout formLayout;
    private TextField txtCvr;
    private TextField txtEan;
    private TextField txtStreetname;
    private TextField txtPostalCode;
    private TextField txtCity;
    private TextField txtOther;
    private CssLayout mapHolder;
    private Button btnSave;
    private Button btnDelete;

    public ClientDataDesign() {
        Design.read(this);
    }

    public VerticalLayout getCardHolder() {
        return cardHolder;
    }

    public Label getLblTitle() {
        return lblTitle;
    }

    public VerticalLayout getContainer() {
        return container;
    }

    public TextField getTxtName() {
        return txtName;
    }

    public TextField getTxtContactName() {
        return txtContactName;
    }

    public Button getBtnEdit() {
        return btnEdit;
    }

    public CssLayout getCssHider() {
        return cssHider;
    }

    public FormLayout getFormLayout() {
        return formLayout;
    }

    public TextField getTxtCvr() {
        return txtCvr;
    }

    public TextField getTxtEan() {
        return txtEan;
    }

    public TextField getTxtStreetname() {
        return txtStreetname;
    }

    public TextField getTxtPostalCode() {
        return txtPostalCode;
    }

    public TextField getTxtCity() {
        return txtCity;
    }

    public TextField getTxtOther() {
        return txtOther;
    }

    public CssLayout getMapHolder() {
        return mapHolder;
    }

    public Button getBtnSave() {
        return btnSave;
    }

    public Button getBtnDelete() {
        return btnDelete;
    }

}
