package dk.trustworks.invoicewebui.web.admin.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Button;
import server.droporchoose.UploadComponent;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Label;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class DocumentUpload extends VerticalLayout {
    private VerticalLayout cardHolder;
    private TextField txtName;
    private UploadComponent uploadComponent;
    private VerticalLayout vlUploadComplete;
    private Button btnRemoveUpload;
    private Label lblFilename;
    private Button btnUpload;

    public DocumentUpload() {
        Design.read(this);
    }

    public VerticalLayout getCardHolder() {
        return cardHolder;
    }

    public TextField getTxtName() {
        return txtName;
    }

    public UploadComponent getUploadComponent() {
        return uploadComponent;
    }

    public VerticalLayout getVlUploadComplete() {
        return vlUploadComplete;
    }

    public Button getBtnRemoveUpload() {
        return btnRemoveUpload;
    }

    public Label getLblFilename() {
        return lblFilename;
    }

    public Button getBtnUpload() {
        return btnUpload;
    }

}
