package dk.trustworks.invoicewebui.web.admin.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.*;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class TalentPassionScoringDesign extends VerticalLayout {
    private VerticalLayout cardHolder;
    private CssLayout imgUser;
    private Image imgDna;
    private Label lblDna;
    private VerticalLayout vlChoiceDNA;
    private Slider rbgPerformanceDNA;
    private Slider rbgPotentialDNA;
    private Button btnDNA;
    private Image imgCustomer;
    private Label lblCustomer;
    private VerticalLayout vlChoiceCustomer;
    private Slider rbgPerformanceCustomer;
    private Slider rbgPotentialCustomer;
    private Button btnCustomer;
    private Image imgTeam;
    private Label lblTeam;
    private VerticalLayout vlChoiceTeam;
    private Slider rbgPerformanceTeam;
    private Slider rbgPotentialTeam;
    private Button btnTeam;

    public TalentPassionScoringDesign() {
        Design.read(this);
    }

    public VerticalLayout getCardHolder() {
        return cardHolder;
    }

    public CssLayout getImgUser() {
        return imgUser;
    }

    public Image getImgDna() {
        return imgDna;
    }

    public Label getLblDna() {
        return lblDna;
    }

    public VerticalLayout getVlChoiceDNA() {
        return vlChoiceDNA;
    }

    public Slider getRbgPerformanceDNA() {
        return rbgPerformanceDNA;
    }

    public Slider getRbgPotentialDNA() {
        return rbgPotentialDNA;
    }

    public Button getBtnDNA() {
        return btnDNA;
    }

    public Image getImgCustomer() {
        return imgCustomer;
    }

    public Label getLblCustomer() {
        return lblCustomer;
    }

    public VerticalLayout getVlChoiceCustomer() {
        return vlChoiceCustomer;
    }

    public Slider getRbgPerformanceCustomer() {
        return rbgPerformanceCustomer;
    }

    public Slider getRbgPotentialCustomer() {
        return rbgPotentialCustomer;
    }

    public Button getBtnCustomer() {
        return btnCustomer;
    }

    public Image getImgTeam() {
        return imgTeam;
    }

    public Label getLblTeam() {
        return lblTeam;
    }

    public VerticalLayout getVlChoiceTeam() {
        return vlChoiceTeam;
    }

    public Slider getRbgPerformanceTeam() {
        return rbgPerformanceTeam;
    }

    public Slider getRbgPotentialTeam() {
        return rbgPotentialTeam;
    }

    public Button getBtnTeam() {
        return btnTeam;
    }

}
