package dk.trustworks.invoicewebui.web.admin.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.*;
import com.vaadin.ui.declarative.Design;
import dk.trustworks.invoicewebui.model.Team;
import dk.trustworks.invoicewebui.model.TeamRole;
import dk.trustworks.invoicewebui.model.enums.TeamMemberType;
import dk.trustworks.invoicewebui.web.admin.model.TeamRolesGridItem;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class TeamRolesCardDesign extends VerticalLayout {
    private VerticalLayout cardHolder;
    private Label lblTitle;
    private VerticalLayout container;
    private Grid<dk.trustworks.invoicewebui.web.admin.model.TeamRolesGridItem> gridTeamRoles;
    private HorizontalLayout hlAddBar;

    private ComboBox<dk.trustworks.invoicewebui.model.Team> cbTeam;
    private ComboBox<dk.trustworks.invoicewebui.model.enums.TeamMemberType> cbTeamRole;
    private DateField dfStartDate;
    private DateField dfEndDate;
    private Button btnCreate;
    private Button btnDelete;

    public TeamRolesCardDesign() {
        Design.read(this);
    }

    public VerticalLayout getCardHolder() {
        return cardHolder;
    }

    public Label getLblTitle() {
        return lblTitle;
    }

    public VerticalLayout getContainer() {
        return container;
    }

    public HorizontalLayout getHlAddBar() {
        return hlAddBar;
    }

    public Button getBtnCreate() {
        return btnCreate;
    }

    public Button getBtnDelete() {
        return btnDelete;
    }

    public ComboBox<Team> getCbTeam() {
        return cbTeam;
    }

    public ComboBox<TeamMemberType> getCbTeamRole() {
        return cbTeamRole;
    }

    public DateField getDfStartDate() {
        return dfStartDate;
    }

    public DateField getDfEndDate() {
        return dfEndDate;
    }

    public Grid<TeamRolesGridItem> getGridTeamRoles() {
        return gridTeamRoles;
    }
}
