package dk.trustworks.invoicewebui.web.admin.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.*;
import com.vaadin.ui.declarative.Design;
import dk.trustworks.invoicewebui.model.enums.StatusType;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class UserStatusCardDesign extends VerticalLayout {
    private VerticalLayout cardHolder;
    private Label lblTitle;
    private VerticalLayout container;
    private Grid<dk.trustworks.invoicewebui.model.UserStatus> gridSalaries;
    private HorizontalLayout hlAddBar;
    private DateField dfDate;
    private ComboBox<StatusType> cbStatus;
    private ComboBox<dk.trustworks.invoicewebui.model.enums.ConsultantType> cbType;
    private TextField txtAllocation;
    private Button btnCreate;
    private Button btnDelete;

    public UserStatusCardDesign() {
        Design.read(this);
    }

    public VerticalLayout getCardHolder() {
        return cardHolder;
    }

    public Label getLblTitle() {
        return lblTitle;
    }

    public VerticalLayout getContainer() {
        return container;
    }

    public Grid<dk.trustworks.invoicewebui.model.UserStatus> getGridSalaries() {
        return gridSalaries;
    }

    public HorizontalLayout getHlAddBar() {
        return hlAddBar;
    }

    public DateField getDfDate() {
        return dfDate;
    }

    public ComboBox<StatusType> getCbStatus() {
        return cbStatus;
    }

    public ComboBox<dk.trustworks.invoicewebui.model.enums.ConsultantType> getCbType() {
        return cbType;
    }

    public TextField getTxtAllocation() {
        return txtAllocation;
    }

    public Button getBtnCreate() {
        return btnCreate;
    }

    public Button getBtnDelete() {
        return btnDelete;
    }

}
