package dk.trustworks.invoicewebui.web.admin.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.DateField;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.annotations.PropertyId;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class UserInfoCardDesign extends VerticalLayout {
    private VerticalLayout cardHolder;
    private Label lblTitle;
    private VerticalLayout container;
    private TextField txtFirstname;
    private TextField txtLastname;
    private TextField txtEmail;
    private TextField txtUsername;
    @PropertyId("name")
    private ComboBox<allbegray.slack.type.User> cbSlackID;
    private DateField dfBirthday;
    private CheckBox cbActive;
    private Button btnUpdate;

    public UserInfoCardDesign() {
        Design.read(this);
    }

    public VerticalLayout getCardHolder() {
        return cardHolder;
    }

    public Label getLblTitle() {
        return lblTitle;
    }

    public VerticalLayout getContainer() {
        return container;
    }

    public TextField getTxtFirstname() {
        return txtFirstname;
    }

    public TextField getTxtLastname() {
        return txtLastname;
    }

    public TextField getTxtEmail() {
        return txtEmail;
    }

    public TextField getTxtUsername() {
        return txtUsername;
    }

    public ComboBox<allbegray.slack.type.User> getCbSlackID() {
        return cbSlackID;
    }

    public DateField getDfBirthday() {
        return dfBirthday;
    }

    public CheckBox getCbActive() {
        return cbActive;
    }

    public Button getBtnUpdate() {
        return btnUpdate;
    }

}
