package dk.trustworks.invoicewebui.web.admin.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Grid;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.DateField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class UserStatusCardDesign extends VerticalLayout {
    private VerticalLayout cardHolder;
    private Label lblTitle;
    private VerticalLayout container;
    private Grid<dk.trustworks.invoicewebui.model.UserStatus> gridSalaries;
    private HorizontalLayout hlAddBar;
    private DateField dfDate;
    private ComboBox<dk.trustworks.invoicewebui.model.StatusType> cbStatus;
    private TextField txtAllocation;
    private Button btnCreate;
    private Button btnDelete;

    public UserStatusCardDesign() {
        Design.read(this);
    }

    public VerticalLayout getCardHolder() {
        return cardHolder;
    }

    public Label getLblTitle() {
        return lblTitle;
    }

    public VerticalLayout getContainer() {
        return container;
    }

    public Grid<dk.trustworks.invoicewebui.model.UserStatus> getGridSalaries() {
        return gridSalaries;
    }

    public HorizontalLayout getHlAddBar() {
        return hlAddBar;
    }

    public DateField getDfDate() {
        return dfDate;
    }

    public ComboBox<dk.trustworks.invoicewebui.model.StatusType> getCbStatus() {
        return cbStatus;
    }

    public TextField getTxtAllocation() {
        return txtAllocation;
    }

    public Button getBtnCreate() {
        return btnCreate;
    }

    public Button getBtnDelete() {
        return btnDelete;
    }

}
