package dk.trustworks.invoicewebui.web.admin.components;

import com.slack.api.model.User;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.annotations.PropertyId;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.DateField;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.Button;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class UserInfoCardDesign extends VerticalLayout {
    private VerticalLayout cardHolder;
    private Label lblTitle;
    private VerticalLayout container;
    private TextField txtFirstname;
    private TextField txtLastname;
    private ComboBox<String> cbGender;
    private TextField txtEmail;
    private TextField txtPhone;
    private TextField txtUsername;
    private CheckBox cbPension;
    private CheckBox cbHealthcare;
    private TextField txtDefects;
    private TextField txtPensiondetails;
    private CheckBox cbPhotoconcent;
    protected TextField txtOther;
    @PropertyId("name")
    private ComboBox<User> cbSlackID;
    private TextField txtAccountNumber;
    private Label lblAccountText;
    private DateField dfBirthday;
    private CheckBox cbActive;
    private Button btnUpdate;
    private TextField txtCpr;

    public UserInfoCardDesign() {
        Design.read(this);
    }

    public VerticalLayout getCardHolder() {
        return cardHolder;
    }

    public Label getLblTitle() {
        return lblTitle;
    }

    public VerticalLayout getContainer() {
        return container;
    }

    public TextField getTxtFirstname() {
        return txtFirstname;
    }

    public TextField getTxtLastname() {
        return txtLastname;
    }

    public ComboBox<String> getCbGender() {
        return cbGender;
    }

    public TextField getTxtEmail() {
        return txtEmail;
    }

    public TextField getTxtUsername() {
        return txtUsername;
    }

    public ComboBox<User> getCbSlackID() {
        return cbSlackID;
    }

    public TextField getTxtAccountNumber() { return txtAccountNumber; }

    public Label getLblAccountText() { return lblAccountText; }

    public DateField getDfBirthday() {
        return dfBirthday;
    }

    public CheckBox getCbActive() {
        return cbActive;
    }

    public Button getBtnUpdate() {
        return btnUpdate;
    }

    public TextField getTxtPhone() {
        return txtPhone;
    }

    public void setTxtPhone(TextField txtPhone) {
        this.txtPhone = txtPhone;
    }

    public CheckBox getCbPension() {
        return cbPension;
    }

    public void setCbPension(CheckBox cbPension) {
        this.cbPension = cbPension;
    }

    public CheckBox getCbHealthcare() {
        return cbHealthcare;
    }

    public void setCbHealthcare(CheckBox cbHealthcare) {
        this.cbHealthcare = cbHealthcare;
    }

    public TextField getTxtDefects() {
        return txtDefects;
    }

    public void setTxtDefects(TextField txtDefects) {
        this.txtDefects = txtDefects;
    }

    public TextField getTxtPensiondetails() {
        return txtPensiondetails;
    }

    public void setTxtPensiondetails(TextField txtPensiondetails) {
        this.txtPensiondetails = txtPensiondetails;
    }

    public CheckBox getCbPhotoconcent() {
        return cbPhotoconcent;
    }

    public void setCbPhotoconcent(CheckBox cbPhotoconcent) {
        this.cbPhotoconcent = cbPhotoconcent;
    }

    public TextField getTxtOther() {
        return txtOther;
    }

    public void setTxtOther(TextField txtOther) {
        this.txtOther = txtOther;
    }

    public TextField getTxtCpr() {
        return txtCpr;
    }

    public void setTxtCpr(TextField txtCpr) {
        this.txtCpr = txtCpr;
    }
}
