package dk.trustworks.invoicewebui.web.admin.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.*;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class UserSalaryCardDesign extends VerticalLayout {
    private VerticalLayout cardHolder;
    private Label lblTitle;
    private VerticalLayout container;
    private Grid<dk.trustworks.invoicewebui.model.Salary> gridSalaries;
    private HorizontalLayout hlAddBar;
    private DateField dfDate;
    private TextField txtSalary;
    private Button btnAddSalary;
    private Button btnDelete;

    public UserSalaryCardDesign() {
        Design.read(this);
    }

    public VerticalLayout getCardHolder() {
        return cardHolder;
    }

    public Label getLblTitle() {
        return lblTitle;
    }

    public VerticalLayout getContainer() {
        return container;
    }

    public Grid<dk.trustworks.invoicewebui.model.Salary> getGridSalaries() {
        return gridSalaries;
    }

    public HorizontalLayout getHlAddBar() {
        return hlAddBar;
    }

    public DateField getDfDate() {
        return dfDate;
    }

    public TextField getTxtSalary() {
        return txtSalary;
    }

    public Button getBtnAddSalary() {
        return btnAddSalary;
    }

    public Button getBtnDelete() {
        return btnDelete;
    }

}
